// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// PostService is an autogenerated mock type for the PostService type
type PostService struct {
	mock.Mock
}

type PostService_Expecter struct {
	mock *mock.Mock
}

func (_m *PostService) EXPECT() *PostService_Expecter {
	return &PostService_Expecter{mock: &_m.Mock}
}

// AddPhotosPost provides a mock function with given fields: ctx, postID, photos
func (_m *PostService) AddPhotosPost(ctx context.Context, postID int, photos []core.Photo) ([]core.Photo, error) {
	ret := _m.Called(ctx, postID, photos)

	var r0 []core.Photo
	if rf, ok := ret.Get(0).(func(context.Context, int, []core.Photo) []core.Photo); ok {
		r0 = rf(ctx, postID, photos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Photo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []core.Photo) error); ok {
		r1 = rf(ctx, postID, photos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_AddPhotosPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPhotosPost'
type PostService_AddPhotosPost_Call struct {
	*mock.Call
}

// AddPhotosPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
//   - photos []core.Photo
func (_e *PostService_Expecter) AddPhotosPost(ctx interface{}, postID interface{}, photos interface{}) *PostService_AddPhotosPost_Call {
	return &PostService_AddPhotosPost_Call{Call: _e.mock.On("AddPhotosPost", ctx, postID, photos)}
}

func (_c *PostService_AddPhotosPost_Call) Run(run func(ctx context.Context, postID int, photos []core.Photo)) *PostService_AddPhotosPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]core.Photo))
	})
	return _c
}

func (_c *PostService_AddPhotosPost_Call) Return(_a0 []core.Photo, _a1 error) *PostService_AddPhotosPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// AddToFavourites provides a mock function with given fields: ctx, postFavourite
func (_m *PostService) AddToFavourites(ctx context.Context, postFavourite core.PostFavourite) (core.PostDetails, error) {
	ret := _m.Called(ctx, postFavourite)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.PostFavourite) core.PostDetails); ok {
		r0 = rf(ctx, postFavourite)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.PostFavourite) error); ok {
		r1 = rf(ctx, postFavourite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_AddToFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFavourites'
type PostService_AddToFavourites_Call struct {
	*mock.Call
}

// AddToFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - postFavourite core.PostFavourite
func (_e *PostService_Expecter) AddToFavourites(ctx interface{}, postFavourite interface{}) *PostService_AddToFavourites_Call {
	return &PostService_AddToFavourites_Call{Call: _e.mock.On("AddToFavourites", ctx, postFavourite)}
}

func (_c *PostService_AddToFavourites_Call) Run(run func(ctx context.Context, postFavourite core.PostFavourite)) *PostService_AddToFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.PostFavourite))
	})
	return _c
}

func (_c *PostService_AddToFavourites_Call) Return(_a0 core.PostDetails, _a1 error) *PostService_AddToFavourites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreatePost provides a mock function with given fields: ctx, postDetails
func (_m *PostService) CreatePost(ctx context.Context, postDetails core.PostDetails) (core.PostDetails, error) {
	ret := _m.Called(ctx, postDetails)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.PostDetails) core.PostDetails); ok {
		r0 = rf(ctx, postDetails)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.PostDetails) error); ok {
		r1 = rf(ctx, postDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type PostService_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - postDetails core.PostDetails
func (_e *PostService_Expecter) CreatePost(ctx interface{}, postDetails interface{}) *PostService_CreatePost_Call {
	return &PostService_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, postDetails)}
}

func (_c *PostService_CreatePost_Call) Run(run func(ctx context.Context, postDetails core.PostDetails)) *PostService_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.PostDetails))
	})
	return _c
}

func (_c *PostService_CreatePost_Call) Return(_a0 core.PostDetails, _a1 error) *PostService_CreatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteFromFavourites provides a mock function with given fields: ctx, post
func (_m *PostService) DeleteFromFavourites(ctx context.Context, post core.PostFavourite) error {
	ret := _m.Called(ctx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.PostFavourite) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostService_DeleteFromFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromFavourites'
type PostService_DeleteFromFavourites_Call struct {
	*mock.Call
}

// DeleteFromFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - post core.PostFavourite
func (_e *PostService_Expecter) DeleteFromFavourites(ctx interface{}, post interface{}) *PostService_DeleteFromFavourites_Call {
	return &PostService_DeleteFromFavourites_Call{Call: _e.mock.On("DeleteFromFavourites", ctx, post)}
}

func (_c *PostService_DeleteFromFavourites_Call) Run(run func(ctx context.Context, post core.PostFavourite)) *PostService_DeleteFromFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.PostFavourite))
	})
	return _c
}

func (_c *PostService_DeleteFromFavourites_Call) Return(_a0 error) *PostService_DeleteFromFavourites_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeletePost provides a mock function with given fields: ctx, post
func (_m *PostService) DeletePost(ctx context.Context, post core.Post) error {
	ret := _m.Called(ctx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Post) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostService_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type PostService_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post core.Post
func (_e *PostService_Expecter) DeletePost(ctx interface{}, post interface{}) *PostService_DeletePost_Call {
	return &PostService_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, post)}
}

func (_c *PostService_DeletePost_Call) Run(run func(ctx context.Context, post core.Post)) *PostService_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Post))
	})
	return _c
}

func (_c *PostService_DeletePost_Call) Return(_a0 error) *PostService_DeletePost_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetAllPosts provides a mock function with given fields: ctx, userID, params
func (_m *PostService) GetAllPosts(ctx context.Context, userID int, params core.GetAllPostsParams) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, userID, params)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, core.GetAllPostsParams) []core.PostDetails); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, core.GetAllPostsParams) int); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, core.GetAllPostsParams) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PostService_GetAllPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPosts'
type PostService_GetAllPosts_Call struct {
	*mock.Call
}

// GetAllPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - params core.GetAllPostsParams
func (_e *PostService_Expecter) GetAllPosts(ctx interface{}, userID interface{}, params interface{}) *PostService_GetAllPosts_Call {
	return &PostService_GetAllPosts_Call{Call: _e.mock.On("GetAllPosts", ctx, userID, params)}
}

func (_c *PostService_GetAllPosts_Call) Run(run func(ctx context.Context, userID int, params core.GetAllPostsParams)) *PostService_GetAllPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(core.GetAllPostsParams))
	})
	return _c
}

func (_c *PostService_GetAllPosts_Call) Return(_a0 []core.PostDetails, _a1 int, _a2 error) *PostService_GetAllPosts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// GetFavouritePosts provides a mock function with given fields: ctx, userID, params
func (_m *PostService) GetFavouritePosts(ctx context.Context, userID int, params core.GetAllPostsParams) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, userID, params)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, core.GetAllPostsParams) []core.PostDetails); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, core.GetAllPostsParams) int); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, core.GetAllPostsParams) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PostService_GetFavouritePosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavouritePosts'
type PostService_GetFavouritePosts_Call struct {
	*mock.Call
}

// GetFavouritePosts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - params core.GetAllPostsParams
func (_e *PostService_Expecter) GetFavouritePosts(ctx interface{}, userID interface{}, params interface{}) *PostService_GetFavouritePosts_Call {
	return &PostService_GetFavouritePosts_Call{Call: _e.mock.On("GetFavouritePosts", ctx, userID, params)}
}

func (_c *PostService_GetFavouritePosts_Call) Run(run func(ctx context.Context, userID int, params core.GetAllPostsParams)) *PostService_GetFavouritePosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(core.GetAllPostsParams))
	})
	return _c
}

func (_c *PostService_GetFavouritePosts_Call) Return(_a0 []core.PostDetails, _a1 int, _a2 error) *PostService_GetFavouritePosts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// GetPhotosPost provides a mock function with given fields: ctx, postID
func (_m *PostService) GetPhotosPost(ctx context.Context, postID int) ([]core.Photo, error) {
	ret := _m.Called(ctx, postID)

	var r0 []core.Photo
	if rf, ok := ret.Get(0).(func(context.Context, int) []core.Photo); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Photo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_GetPhotosPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPhotosPost'
type PostService_GetPhotosPost_Call struct {
	*mock.Call
}

// GetPhotosPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
func (_e *PostService_Expecter) GetPhotosPost(ctx interface{}, postID interface{}) *PostService_GetPhotosPost_Call {
	return &PostService_GetPhotosPost_Call{Call: _e.mock.On("GetPhotosPost", ctx, postID)}
}

func (_c *PostService_GetPhotosPost_Call) Run(run func(ctx context.Context, postID int)) *PostService_GetPhotosPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *PostService_GetPhotosPost_Call) Return(_a0 []core.Photo, _a1 error) *PostService_GetPhotosPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPhotosPostByPhotoID provides a mock function with given fields: ctx, postID, photoID
func (_m *PostService) GetPhotosPostByPhotoID(ctx context.Context, postID int, photoID int) (core.Photo, error) {
	ret := _m.Called(ctx, postID, photoID)

	var r0 core.Photo
	if rf, ok := ret.Get(0).(func(context.Context, int, int) core.Photo); ok {
		r0 = rf(ctx, postID, photoID)
	} else {
		r0 = ret.Get(0).(core.Photo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, postID, photoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_GetPhotosPostByPhotoID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPhotosPostByPhotoID'
type PostService_GetPhotosPostByPhotoID_Call struct {
	*mock.Call
}

// GetPhotosPostByPhotoID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
//   - photoID int
func (_e *PostService_Expecter) GetPhotosPostByPhotoID(ctx interface{}, postID interface{}, photoID interface{}) *PostService_GetPhotosPostByPhotoID_Call {
	return &PostService_GetPhotosPostByPhotoID_Call{Call: _e.mock.On("GetPhotosPostByPhotoID", ctx, postID, photoID)}
}

func (_c *PostService_GetPhotosPostByPhotoID_Call) Run(run func(ctx context.Context, postID int, photoID int)) *PostService_GetPhotosPostByPhotoID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *PostService_GetPhotosPostByPhotoID_Call) Return(_a0 core.Photo, _a1 error) *PostService_GetPhotosPostByPhotoID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPostByID provides a mock function with given fields: ctx, postID, userID
func (_m *PostService) GetPostByID(ctx context.Context, postID int, userID int) (core.PostDetails, error) {
	ret := _m.Called(ctx, postID, userID)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, int) core.PostDetails); ok {
		r0 = rf(ctx, postID, userID)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, postID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_GetPostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostByID'
type PostService_GetPostByID_Call struct {
	*mock.Call
}

// GetPostByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
//   - userID int
func (_e *PostService_Expecter) GetPostByID(ctx interface{}, postID interface{}, userID interface{}) *PostService_GetPostByID_Call {
	return &PostService_GetPostByID_Call{Call: _e.mock.On("GetPostByID", ctx, postID, userID)}
}

func (_c *PostService_GetPostByID_Call) Run(run func(ctx context.Context, postID int, userID int)) *PostService_GetPostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *PostService_GetPostByID_Call) Return(_a0 core.PostDetails, _a1 error) *PostService_GetPostByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserPosts provides a mock function with given fields: ctx, id
func (_m *PostService) GetUserPosts(ctx context.Context, id int) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, id)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int) []core.PostDetails); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PostService_GetUserPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosts'
type PostService_GetUserPosts_Call struct {
	*mock.Call
}

// GetUserPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *PostService_Expecter) GetUserPosts(ctx interface{}, id interface{}) *PostService_GetUserPosts_Call {
	return &PostService_GetUserPosts_Call{Call: _e.mock.On("GetUserPosts", ctx, id)}
}

func (_c *PostService_GetUserPosts_Call) Run(run func(ctx context.Context, id int)) *PostService_GetUserPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *PostService_GetUserPosts_Call) Return(posts []core.PostDetails, count int, err error) *PostService_GetUserPosts_Call {
	_c.Call.Return(posts, count, err)
	return _c
}

// UpdatePost provides a mock function with given fields: ctx, updateRequestPost, updateRequestPhotos
func (_m *PostService) UpdatePost(ctx context.Context, updateRequestPost core.UpdateRequestPost, updateRequestPhotos core.UpdateRequestPhotos) (core.PostDetails, error) {
	ret := _m.Called(ctx, updateRequestPost, updateRequestPhotos)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateRequestPost, core.UpdateRequestPhotos) core.PostDetails); ok {
		r0 = rf(ctx, updateRequestPost, updateRequestPhotos)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.UpdateRequestPost, core.UpdateRequestPhotos) error); ok {
		r1 = rf(ctx, updateRequestPost, updateRequestPhotos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostService_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type PostService_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - updateRequestPost core.UpdateRequestPost
//   - updateRequestPhotos core.UpdateRequestPhotos
func (_e *PostService_Expecter) UpdatePost(ctx interface{}, updateRequestPost interface{}, updateRequestPhotos interface{}) *PostService_UpdatePost_Call {
	return &PostService_UpdatePost_Call{Call: _e.mock.On("UpdatePost", ctx, updateRequestPost, updateRequestPhotos)}
}

func (_c *PostService_UpdatePost_Call) Run(run func(ctx context.Context, updateRequestPost core.UpdateRequestPost, updateRequestPhotos core.UpdateRequestPhotos)) *PostService_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.UpdateRequestPost), args[2].(core.UpdateRequestPhotos))
	})
	return _c
}

func (_c *PostService_UpdatePost_Call) Return(_a0 core.PostDetails, _a1 error) *PostService_UpdatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewPostService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostService creates a new instance of PostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostService(t mockConstructorTestingTNewPostService) *PostService {
	mock := &PostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
