// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UpdateRefreshSessionParam is an autogenerated mock type for the UpdateRefreshSessionParam type
type UpdateRefreshSessionParam struct {
	mock.Mock
}

type UpdateRefreshSessionParam_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateRefreshSessionParam) EXPECT() *UpdateRefreshSessionParam_Expecter {
	return &UpdateRefreshSessionParam_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *UpdateRefreshSessionParam) Execute(_a0 *gorm.DB) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRefreshSessionParam_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateRefreshSessionParam_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *gorm.DB
func (_e *UpdateRefreshSessionParam_Expecter) Execute(_a0 interface{}) *UpdateRefreshSessionParam_Execute_Call {
	return &UpdateRefreshSessionParam_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *UpdateRefreshSessionParam_Execute_Call) Run(run func(_a0 *gorm.DB)) *UpdateRefreshSessionParam_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *UpdateRefreshSessionParam_Execute_Call) Return(_a0 error) *UpdateRefreshSessionParam_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUpdateRefreshSessionParam interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateRefreshSessionParam creates a new instance of UpdateRefreshSessionParam. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateRefreshSessionParam(t mockConstructorTestingTNewUpdateRefreshSessionParam) *UpdateRefreshSessionParam {
	mock := &UpdateRefreshSessionParam{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
