// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// UserFavouriteStore is an autogenerated mock type for the UserFavouriteStore type
type UserFavouriteStore struct {
	mock.Mock
}

type UserFavouriteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserFavouriteStore) EXPECT() *UserFavouriteStore_Expecter {
	return &UserFavouriteStore_Expecter{mock: &_m.Mock}
}

// AddUserToFavourite provides a mock function with given fields: ctx, personID, userID
func (_m *UserFavouriteStore) AddUserToFavourite(ctx context.Context, personID int, userID int) error {
	ret := _m.Called(ctx, personID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, personID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserFavouriteStore_AddUserToFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToFavourite'
type UserFavouriteStore_AddUserToFavourite_Call struct {
	*mock.Call
}

// AddUserToFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - personID int
//   - userID int
func (_e *UserFavouriteStore_Expecter) AddUserToFavourite(ctx interface{}, personID interface{}, userID interface{}) *UserFavouriteStore_AddUserToFavourite_Call {
	return &UserFavouriteStore_AddUserToFavourite_Call{Call: _e.mock.On("AddUserToFavourite", ctx, personID, userID)}
}

func (_c *UserFavouriteStore_AddUserToFavourite_Call) Run(run func(ctx context.Context, personID int, userID int)) *UserFavouriteStore_AddUserToFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UserFavouriteStore_AddUserToFavourite_Call) Return(err error) *UserFavouriteStore_AddUserToFavourite_Call {
	_c.Call.Return(err)
	return _c
}

// DeleteUserFromFavourite provides a mock function with given fields: ctx, personID, userID
func (_m *UserFavouriteStore) DeleteUserFromFavourite(ctx context.Context, personID int, userID int) error {
	ret := _m.Called(ctx, personID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, personID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserFavouriteStore_DeleteUserFromFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserFromFavourite'
type UserFavouriteStore_DeleteUserFromFavourite_Call struct {
	*mock.Call
}

// DeleteUserFromFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - personID int
//   - userID int
func (_e *UserFavouriteStore_Expecter) DeleteUserFromFavourite(ctx interface{}, personID interface{}, userID interface{}) *UserFavouriteStore_DeleteUserFromFavourite_Call {
	return &UserFavouriteStore_DeleteUserFromFavourite_Call{Call: _e.mock.On("DeleteUserFromFavourite", ctx, personID, userID)}
}

func (_c *UserFavouriteStore_DeleteUserFromFavourite_Call) Run(run func(ctx context.Context, personID int, userID int)) *UserFavouriteStore_DeleteUserFromFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UserFavouriteStore_DeleteUserFromFavourite_Call) Return(err error) *UserFavouriteStore_DeleteUserFromFavourite_Call {
	_c.Call.Return(err)
	return _c
}

// GetFavouriteUsers provides a mock function with given fields: ctx, userID, params
func (_m *UserFavouriteStore) GetFavouriteUsers(ctx context.Context, userID int, params core.GetFavourites) ([]core.User, error) {
	ret := _m.Called(ctx, userID, params)

	var r0 []core.User
	if rf, ok := ret.Get(0).(func(context.Context, int, core.GetFavourites) []core.User); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, core.GetFavourites) error); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFavouriteStore_GetFavouriteUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavouriteUsers'
type UserFavouriteStore_GetFavouriteUsers_Call struct {
	*mock.Call
}

// GetFavouriteUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - params core.GetFavourites
func (_e *UserFavouriteStore_Expecter) GetFavouriteUsers(ctx interface{}, userID interface{}, params interface{}) *UserFavouriteStore_GetFavouriteUsers_Call {
	return &UserFavouriteStore_GetFavouriteUsers_Call{Call: _e.mock.On("GetFavouriteUsers", ctx, userID, params)}
}

func (_c *UserFavouriteStore_GetFavouriteUsers_Call) Run(run func(ctx context.Context, userID int, params core.GetFavourites)) *UserFavouriteStore_GetFavouriteUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(core.GetFavourites))
	})
	return _c
}

func (_c *UserFavouriteStore_GetFavouriteUsers_Call) Return(favouriteUsers []core.User, err error) *UserFavouriteStore_GetFavouriteUsers_Call {
	_c.Call.Return(favouriteUsers, err)
	return _c
}

type mockConstructorTestingTNewUserFavouriteStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserFavouriteStore creates a new instance of UserFavouriteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserFavouriteStore(t mockConstructorTestingTNewUserFavouriteStore) *UserFavouriteStore {
	mock := &UserFavouriteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
