// Code generated by mockery v2.53.0. DO NOT EDIT.

package core

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// MockPostFavouriteStore is an autogenerated mock type for the PostFavouriteStore type
type MockPostFavouriteStore struct {
	mock.Mock
}

type MockPostFavouriteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostFavouriteStore) EXPECT() *MockPostFavouriteStore_Expecter {
	return &MockPostFavouriteStore_Expecter{mock: &_m.Mock}
}

// AddToFavourites provides a mock function with given fields: ctx, postFavourite
func (_m *MockPostFavouriteStore) AddToFavourites(ctx context.Context, postFavourite core.PostFavourite) error {
	ret := _m.Called(ctx, postFavourite)

	if len(ret) == 0 {
		panic("no return value specified for AddToFavourites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.PostFavourite) error); ok {
		r0 = rf(ctx, postFavourite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostFavouriteStore_AddToFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFavourites'
type MockPostFavouriteStore_AddToFavourites_Call struct {
	*mock.Call
}

// AddToFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - postFavourite core.PostFavourite
func (_e *MockPostFavouriteStore_Expecter) AddToFavourites(ctx interface{}, postFavourite interface{}) *MockPostFavouriteStore_AddToFavourites_Call {
	return &MockPostFavouriteStore_AddToFavourites_Call{Call: _e.mock.On("AddToFavourites", ctx, postFavourite)}
}

func (_c *MockPostFavouriteStore_AddToFavourites_Call) Run(run func(ctx context.Context, postFavourite core.PostFavourite)) *MockPostFavouriteStore_AddToFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.PostFavourite))
	})
	return _c
}

func (_c *MockPostFavouriteStore_AddToFavourites_Call) Return(_a0 error) *MockPostFavouriteStore_AddToFavourites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostFavouriteStore_AddToFavourites_Call) RunAndReturn(run func(context.Context, core.PostFavourite) error) *MockPostFavouriteStore_AddToFavourites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromFavourites provides a mock function with given fields: ctx, postID, userID
func (_m *MockPostFavouriteStore) DeleteFromFavourites(ctx context.Context, postID int, userID int) error {
	ret := _m.Called(ctx, postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromFavourites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, postID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostFavouriteStore_DeleteFromFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromFavourites'
type MockPostFavouriteStore_DeleteFromFavourites_Call struct {
	*mock.Call
}

// DeleteFromFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
//   - userID int
func (_e *MockPostFavouriteStore_Expecter) DeleteFromFavourites(ctx interface{}, postID interface{}, userID interface{}) *MockPostFavouriteStore_DeleteFromFavourites_Call {
	return &MockPostFavouriteStore_DeleteFromFavourites_Call{Call: _e.mock.On("DeleteFromFavourites", ctx, postID, userID)}
}

func (_c *MockPostFavouriteStore_DeleteFromFavourites_Call) Run(run func(ctx context.Context, postID int, userID int)) *MockPostFavouriteStore_DeleteFromFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockPostFavouriteStore_DeleteFromFavourites_Call) Return(_a0 error) *MockPostFavouriteStore_DeleteFromFavourites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostFavouriteStore_DeleteFromFavourites_Call) RunAndReturn(run func(context.Context, int, int) error) *MockPostFavouriteStore_DeleteFromFavourites_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavouritePosts provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockPostFavouriteStore) GetFavouritePosts(ctx context.Context, userID int, limit int, offset int) ([]core.Post, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFavouritePosts")
	}

	var r0 []core.Post
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]core.Post, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []core.Post); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPostFavouriteStore_GetFavouritePosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavouritePosts'
type MockPostFavouriteStore_GetFavouritePosts_Call struct {
	*mock.Call
}

// GetFavouritePosts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - offset int
func (_e *MockPostFavouriteStore_Expecter) GetFavouritePosts(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockPostFavouriteStore_GetFavouritePosts_Call {
	return &MockPostFavouriteStore_GetFavouritePosts_Call{Call: _e.mock.On("GetFavouritePosts", ctx, userID, limit, offset)}
}

func (_c *MockPostFavouriteStore_GetFavouritePosts_Call) Run(run func(ctx context.Context, userID int, limit int, offset int)) *MockPostFavouriteStore_GetFavouritePosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockPostFavouriteStore_GetFavouritePosts_Call) Return(_a0 []core.Post, _a1 int, _a2 error) *MockPostFavouriteStore_GetFavouritePosts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPostFavouriteStore_GetFavouritePosts_Call) RunAndReturn(run func(context.Context, int, int, int) ([]core.Post, int, error)) *MockPostFavouriteStore_GetFavouritePosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostFavouriteStore creates a new instance of MockPostFavouriteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostFavouriteStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostFavouriteStore {
	mock := &MockPostFavouriteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
