// Code generated by mockery v2.43.2. DO NOT EDIT.

package core

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// MockSeekersStore is an autogenerated mock type for the SeekersStore type
type MockSeekersStore struct {
	mock.Mock
}

type MockSeekersStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeekersStore) EXPECT() *MockSeekersStore_Expecter {
	return &MockSeekersStore_Expecter{mock: &_m.Mock}
}

// CreateEquipment provides a mock function with given fields: ctx, equipment
func (_m *MockSeekersStore) CreateEquipment(ctx context.Context, equipment core.Equipment) (int, error) {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for CreateEquipment")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Equipment) (int, error)); ok {
		return rf(ctx, equipment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Equipment) int); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Equipment) error); ok {
		r1 = rf(ctx, equipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_CreateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEquipment'
type MockSeekersStore_CreateEquipment_Call struct {
	*mock.Call
}

// CreateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment core.Equipment
func (_e *MockSeekersStore_Expecter) CreateEquipment(ctx interface{}, equipment interface{}) *MockSeekersStore_CreateEquipment_Call {
	return &MockSeekersStore_CreateEquipment_Call{Call: _e.mock.On("CreateEquipment", ctx, equipment)}
}

func (_c *MockSeekersStore_CreateEquipment_Call) Run(run func(ctx context.Context, equipment core.Equipment)) *MockSeekersStore_CreateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Equipment))
	})
	return _c
}

func (_c *MockSeekersStore_CreateEquipment_Call) Return(_a0 int, _a1 error) *MockSeekersStore_CreateEquipment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_CreateEquipment_Call) RunAndReturn(run func(context.Context, core.Equipment) (int, error)) *MockSeekersStore_CreateEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeeker provides a mock function with given fields: ctx, seeker
func (_m *MockSeekersStore) CreateSeeker(ctx context.Context, seeker core.Seekers) (core.Seekers, error) {
	ret := _m.Called(ctx, seeker)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeeker")
	}

	var r0 core.Seekers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Seekers) (core.Seekers, error)); ok {
		return rf(ctx, seeker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Seekers) core.Seekers); ok {
		r0 = rf(ctx, seeker)
	} else {
		r0 = ret.Get(0).(core.Seekers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Seekers) error); ok {
		r1 = rf(ctx, seeker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_CreateSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeeker'
type MockSeekersStore_CreateSeeker_Call struct {
	*mock.Call
}

// CreateSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - seeker core.Seekers
func (_e *MockSeekersStore_Expecter) CreateSeeker(ctx interface{}, seeker interface{}) *MockSeekersStore_CreateSeeker_Call {
	return &MockSeekersStore_CreateSeeker_Call{Call: _e.mock.On("CreateSeeker", ctx, seeker)}
}

func (_c *MockSeekersStore_CreateSeeker_Call) Run(run func(ctx context.Context, seeker core.Seekers)) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Seekers))
	})
	return _c
}

func (_c *MockSeekersStore_CreateSeeker_Call) Return(_a0 core.Seekers, _a1 error) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_CreateSeeker_Call) RunAndReturn(run func(context.Context, core.Seekers) (core.Seekers, error)) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeeker provides a mock function with given fields: ctx, id
func (_m *MockSeekersStore) GetSeeker(ctx context.Context, id int) (core.Seekers, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeeker")
	}

	var r0 core.Seekers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (core.Seekers, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) core.Seekers); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(core.Seekers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_GetSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeeker'
type MockSeekersStore_GetSeeker_Call struct {
	*mock.Call
}

// GetSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSeekersStore_Expecter) GetSeeker(ctx interface{}, id interface{}) *MockSeekersStore_GetSeeker_Call {
	return &MockSeekersStore_GetSeeker_Call{Call: _e.mock.On("GetSeeker", ctx, id)}
}

func (_c *MockSeekersStore_GetSeeker_Call) Run(run func(ctx context.Context, id int)) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSeekersStore_GetSeeker_Call) Return(_a0 core.Seekers, _a1 error) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_GetSeeker_Call) RunAndReturn(run func(context.Context, int) (core.Seekers, error)) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeeker provides a mock function with given fields: ctx, seeker
func (_m *MockSeekersStore) UpdateSeeker(ctx context.Context, seeker core.UpdateSeekers) (core.Seekers, error) {
	ret := _m.Called(ctx, seeker)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeeker")
	}

	var r0 core.Seekers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateSeekers) (core.Seekers, error)); ok {
		return rf(ctx, seeker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateSeekers) core.Seekers); ok {
		r0 = rf(ctx, seeker)
	} else {
		r0 = ret.Get(0).(core.Seekers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.UpdateSeekers) error); ok {
		r1 = rf(ctx, seeker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_UpdateSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeeker'
type MockSeekersStore_UpdateSeeker_Call struct {
	*mock.Call
}

// UpdateSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - seeker core.UpdateSeekers
func (_e *MockSeekersStore_Expecter) UpdateSeeker(ctx interface{}, seeker interface{}) *MockSeekersStore_UpdateSeeker_Call {
	return &MockSeekersStore_UpdateSeeker_Call{Call: _e.mock.On("UpdateSeeker", ctx, seeker)}
}

func (_c *MockSeekersStore_UpdateSeeker_Call) Run(run func(ctx context.Context, seeker core.UpdateSeekers)) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.UpdateSeekers))
	})
	return _c
}

func (_c *MockSeekersStore_UpdateSeeker_Call) Return(_a0 core.Seekers, _a1 error) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_UpdateSeeker_Call) RunAndReturn(run func(context.Context, core.UpdateSeekers) (core.Seekers, error)) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeekersStore creates a new instance of MockSeekersStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeekersStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeekersStore {
	mock := &MockSeekersStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
