// Code generated by mockery v2.43.2. DO NOT EDIT.

package core

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// MockSeekersStore is an autogenerated mock type for the SeekersStore type
type MockSeekersStore struct {
	mock.Mock
}

type MockSeekersStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeekersStore) EXPECT() *MockSeekersStore_Expecter {
	return &MockSeekersStore_Expecter{mock: &_m.Mock}
}

// CreateSeeker provides a mock function with given fields: ctx, seeker, equipment
func (_m *MockSeekersStore) CreateSeeker(ctx context.Context, seeker core.Seeker, equipment core.Equipment) (core.Seeker, error) {
	ret := _m.Called(ctx, seeker, equipment)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeeker")
	}

	var r0 core.Seeker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Seeker, core.Equipment) (core.Seeker, error)); ok {
		return rf(ctx, seeker, equipment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Seeker, core.Equipment) core.Seeker); ok {
		r0 = rf(ctx, seeker, equipment)
	} else {
		r0 = ret.Get(0).(core.Seeker)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Seeker, core.Equipment) error); ok {
		r1 = rf(ctx, seeker, equipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_CreateSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeeker'
type MockSeekersStore_CreateSeeker_Call struct {
	*mock.Call
}

// CreateSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - seeker core.Seeker
//   - equipment core.Equipment
func (_e *MockSeekersStore_Expecter) CreateSeeker(ctx interface{}, seeker interface{}, equipment interface{}) *MockSeekersStore_CreateSeeker_Call {
	return &MockSeekersStore_CreateSeeker_Call{Call: _e.mock.On("CreateSeeker", ctx, seeker, equipment)}
}

func (_c *MockSeekersStore_CreateSeeker_Call) Run(run func(ctx context.Context, seeker core.Seeker, equipment core.Equipment)) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Seeker), args[2].(core.Equipment))
	})
	return _c
}

func (_c *MockSeekersStore_CreateSeeker_Call) Return(_a0 core.Seeker, _a1 error) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_CreateSeeker_Call) RunAndReturn(run func(context.Context, core.Seeker, core.Equipment) (core.Seeker, error)) *MockSeekersStore_CreateSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeeker provides a mock function with given fields: ctx, userID
func (_m *MockSeekersStore) DeleteSeeker(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeeker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeekersStore_DeleteSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeeker'
type MockSeekersStore_DeleteSeeker_Call struct {
	*mock.Call
}

// DeleteSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSeekersStore_Expecter) DeleteSeeker(ctx interface{}, userID interface{}) *MockSeekersStore_DeleteSeeker_Call {
	return &MockSeekersStore_DeleteSeeker_Call{Call: _e.mock.On("DeleteSeeker", ctx, userID)}
}

func (_c *MockSeekersStore_DeleteSeeker_Call) Run(run func(ctx context.Context, userID int)) *MockSeekersStore_DeleteSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSeekersStore_DeleteSeeker_Call) Return(_a0 error) *MockSeekersStore_DeleteSeeker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeekersStore_DeleteSeeker_Call) RunAndReturn(run func(context.Context, int) error) *MockSeekersStore_DeleteSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeeker provides a mock function with given fields: ctx, userID
func (_m *MockSeekersStore) GetSeeker(ctx context.Context, userID int) (core.Seeker, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeeker")
	}

	var r0 core.Seeker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (core.Seeker, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) core.Seeker); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(core.Seeker)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_GetSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeeker'
type MockSeekersStore_GetSeeker_Call struct {
	*mock.Call
}

// GetSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSeekersStore_Expecter) GetSeeker(ctx interface{}, userID interface{}) *MockSeekersStore_GetSeeker_Call {
	return &MockSeekersStore_GetSeeker_Call{Call: _e.mock.On("GetSeeker", ctx, userID)}
}

func (_c *MockSeekersStore_GetSeeker_Call) Run(run func(ctx context.Context, userID int)) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSeekersStore_GetSeeker_Call) Return(_a0 core.Seeker, _a1 error) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_GetSeeker_Call) RunAndReturn(run func(context.Context, int) (core.Seeker, error)) *MockSeekersStore_GetSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeeker provides a mock function with given fields: ctx, userID, updateSeeker
func (_m *MockSeekersStore) UpdateSeeker(ctx context.Context, userID int, updateSeeker map[string]interface{}) (core.Seeker, error) {
	ret := _m.Called(ctx, userID, updateSeeker)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeeker")
	}

	var r0 core.Seeker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, map[string]interface{}) (core.Seeker, error)); ok {
		return rf(ctx, userID, updateSeeker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, map[string]interface{}) core.Seeker); ok {
		r0 = rf(ctx, userID, updateSeeker)
	} else {
		r0 = ret.Get(0).(core.Seeker)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, map[string]interface{}) error); ok {
		r1 = rf(ctx, userID, updateSeeker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeekersStore_UpdateSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeeker'
type MockSeekersStore_UpdateSeeker_Call struct {
	*mock.Call
}

// UpdateSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - updateSeeker map[string]interface{}
func (_e *MockSeekersStore_Expecter) UpdateSeeker(ctx interface{}, userID interface{}, updateSeeker interface{}) *MockSeekersStore_UpdateSeeker_Call {
	return &MockSeekersStore_UpdateSeeker_Call{Call: _e.mock.On("UpdateSeeker", ctx, userID, updateSeeker)}
}

func (_c *MockSeekersStore_UpdateSeeker_Call) Run(run func(ctx context.Context, userID int, updateSeeker map[string]interface{})) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockSeekersStore_UpdateSeeker_Call) Return(_a0 core.Seeker, _a1 error) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeekersStore_UpdateSeeker_Call) RunAndReturn(run func(context.Context, int, map[string]interface{}) (core.Seeker, error)) *MockSeekersStore_UpdateSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeekersStore creates a new instance of MockSeekersStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeekersStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeekersStore {
	mock := &MockSeekersStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
