// Code generated by mockery v2.46.2. DO NOT EDIT.

package core

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// MockChatMemberStore is an autogenerated mock type for the ChatMemberStore type
type MockChatMemberStore struct {
	mock.Mock
}

type MockChatMemberStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatMemberStore) EXPECT() *MockChatMemberStore_Expecter {
	return &MockChatMemberStore_Expecter{mock: &_m.Mock}
}

// AddMemberToChat provides a mock function with given fields: ctx, data, userID
func (_m *MockChatMemberStore) AddMemberToChat(ctx context.Context, data core.ChatMember, userID int) (core.ChatMember, error) {
	ret := _m.Called(ctx, data, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMemberToChat")
	}

	var r0 core.ChatMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.ChatMember, int) (core.ChatMember, error)); ok {
		return rf(ctx, data, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.ChatMember, int) core.ChatMember); ok {
		r0 = rf(ctx, data, userID)
	} else {
		r0 = ret.Get(0).(core.ChatMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.ChatMember, int) error); ok {
		r1 = rf(ctx, data, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStore_AddMemberToChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMemberToChat'
type MockChatMemberStore_AddMemberToChat_Call struct {
	*mock.Call
}

// AddMemberToChat is a helper method to define mock.On call
//   - ctx context.Context
//   - data core.ChatMember
//   - userID int
func (_e *MockChatMemberStore_Expecter) AddMemberToChat(ctx interface{}, data interface{}, userID interface{}) *MockChatMemberStore_AddMemberToChat_Call {
	return &MockChatMemberStore_AddMemberToChat_Call{Call: _e.mock.On("AddMemberToChat", ctx, data, userID)}
}

func (_c *MockChatMemberStore_AddMemberToChat_Call) Run(run func(ctx context.Context, data core.ChatMember, userID int)) *MockChatMemberStore_AddMemberToChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.ChatMember), args[2].(int))
	})
	return _c
}

func (_c *MockChatMemberStore_AddMemberToChat_Call) Return(member core.ChatMember, err error) *MockChatMemberStore_AddMemberToChat_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockChatMemberStore_AddMemberToChat_Call) RunAndReturn(run func(context.Context, core.ChatMember, int) (core.ChatMember, error)) *MockChatMemberStore_AddMemberToChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMemberFromChat provides a mock function with given fields: ctx, chatID, userID, currentUserID
func (_m *MockChatMemberStore) DeleteMemberFromChat(ctx context.Context, chatID int, userID int, currentUserID int) error {
	ret := _m.Called(ctx, chatID, userID, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMemberFromChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, chatID, userID, currentUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatMemberStore_DeleteMemberFromChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMemberFromChat'
type MockChatMemberStore_DeleteMemberFromChat_Call struct {
	*mock.Call
}

// DeleteMemberFromChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int
//   - userID int
//   - currentUserID int
func (_e *MockChatMemberStore_Expecter) DeleteMemberFromChat(ctx interface{}, chatID interface{}, userID interface{}, currentUserID interface{}) *MockChatMemberStore_DeleteMemberFromChat_Call {
	return &MockChatMemberStore_DeleteMemberFromChat_Call{Call: _e.mock.On("DeleteMemberFromChat", ctx, chatID, userID, currentUserID)}
}

func (_c *MockChatMemberStore_DeleteMemberFromChat_Call) Run(run func(ctx context.Context, chatID int, userID int, currentUserID int)) *MockChatMemberStore_DeleteMemberFromChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockChatMemberStore_DeleteMemberFromChat_Call) Return(err error) *MockChatMemberStore_DeleteMemberFromChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatMemberStore_DeleteMemberFromChat_Call) RunAndReturn(run func(context.Context, int, int, int) error) *MockChatMemberStore_DeleteMemberFromChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllMembers provides a mock function with given fields: ctx, chatID, userID
func (_m *MockChatMemberStore) GetAllMembers(ctx context.Context, chatID int, userID int) ([]core.ChatMember, error) {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMembers")
	}

	var r0 []core.ChatMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]core.ChatMember, error)); ok {
		return rf(ctx, chatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []core.ChatMember); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.ChatMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStore_GetAllMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMembers'
type MockChatMemberStore_GetAllMembers_Call struct {
	*mock.Call
}

// GetAllMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int
//   - userID int
func (_e *MockChatMemberStore_Expecter) GetAllMembers(ctx interface{}, chatID interface{}, userID interface{}) *MockChatMemberStore_GetAllMembers_Call {
	return &MockChatMemberStore_GetAllMembers_Call{Call: _e.mock.On("GetAllMembers", ctx, chatID, userID)}
}

func (_c *MockChatMemberStore_GetAllMembers_Call) Run(run func(ctx context.Context, chatID int, userID int)) *MockChatMemberStore_GetAllMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockChatMemberStore_GetAllMembers_Call) Return(members []core.ChatMember, err error) *MockChatMemberStore_GetAllMembers_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *MockChatMemberStore_GetAllMembers_Call) RunAndReturn(run func(context.Context, int, int) ([]core.ChatMember, error)) *MockChatMemberStore_GetAllMembers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberInfo provides a mock function with given fields: ctx, chatID, userID, currentUserID
func (_m *MockChatMemberStore) UpdateMemberInfo(ctx context.Context, chatID int, userID int, currentUserID int) (core.ChatMember, error) {
	ret := _m.Called(ctx, chatID, userID, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberInfo")
	}

	var r0 core.ChatMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (core.ChatMember, error)); ok {
		return rf(ctx, chatID, userID, currentUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) core.ChatMember); ok {
		r0 = rf(ctx, chatID, userID, currentUserID)
	} else {
		r0 = ret.Get(0).(core.ChatMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, chatID, userID, currentUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatMemberStore_UpdateMemberInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberInfo'
type MockChatMemberStore_UpdateMemberInfo_Call struct {
	*mock.Call
}

// UpdateMemberInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int
//   - userID int
//   - currentUserID int
func (_e *MockChatMemberStore_Expecter) UpdateMemberInfo(ctx interface{}, chatID interface{}, userID interface{}, currentUserID interface{}) *MockChatMemberStore_UpdateMemberInfo_Call {
	return &MockChatMemberStore_UpdateMemberInfo_Call{Call: _e.mock.On("UpdateMemberInfo", ctx, chatID, userID, currentUserID)}
}

func (_c *MockChatMemberStore_UpdateMemberInfo_Call) Run(run func(ctx context.Context, chatID int, userID int, currentUserID int)) *MockChatMemberStore_UpdateMemberInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockChatMemberStore_UpdateMemberInfo_Call) Return(member core.ChatMember, err error) *MockChatMemberStore_UpdateMemberInfo_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockChatMemberStore_UpdateMemberInfo_Call) RunAndReturn(run func(context.Context, int, int, int) (core.ChatMember, error)) *MockChatMemberStore_UpdateMemberInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatMemberStore creates a new instance of MockChatMemberStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatMemberStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatMemberStore {
	mock := &MockChatMemberStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
