// Code generated by mockery v2.43.2. DO NOT EDIT.

package core

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// MockCommentService is an autogenerated mock type for the CommentService type
type MockCommentService struct {
	mock.Mock
}

type MockCommentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentService) EXPECT() *MockCommentService_Expecter {
	return &MockCommentService_Expecter{mock: &_m.Mock}
}

// CreateComment provides a mock function with given fields: ctx, comment
func (_m *MockCommentService) CreateComment(ctx context.Context, comment core.Comment) (core.Comment, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 core.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Comment) (core.Comment, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Comment) core.Comment); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Get(0).(core.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentService_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockCommentService_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment core.Comment
func (_e *MockCommentService_Expecter) CreateComment(ctx interface{}, comment interface{}) *MockCommentService_CreateComment_Call {
	return &MockCommentService_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, comment)}
}

func (_c *MockCommentService_CreateComment_Call) Run(run func(ctx context.Context, comment core.Comment)) *MockCommentService_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Comment))
	})
	return _c
}

func (_c *MockCommentService_CreateComment_Call) Return(data core.Comment, err error) *MockCommentService_CreateComment_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockCommentService_CreateComment_Call) RunAndReturn(run func(context.Context, core.Comment) (core.Comment, error)) *MockCommentService_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function with given fields: ctx, comments
func (_m *MockCommentService) DeleteComment(ctx context.Context, comments core.Comment) error {
	ret := _m.Called(ctx, comments)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Comment) error); ok {
		r0 = rf(ctx, comments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommentService_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockCommentService_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comments core.Comment
func (_e *MockCommentService_Expecter) DeleteComment(ctx interface{}, comments interface{}) *MockCommentService_DeleteComment_Call {
	return &MockCommentService_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, comments)}
}

func (_c *MockCommentService_DeleteComment_Call) Run(run func(ctx context.Context, comments core.Comment)) *MockCommentService_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Comment))
	})
	return _c
}

func (_c *MockCommentService_DeleteComment_Call) Return(_a0 error) *MockCommentService_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommentService_DeleteComment_Call) RunAndReturn(run func(context.Context, core.Comment) error) *MockCommentService_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllComments provides a mock function with given fields: ctx, params
func (_m *MockCommentService) GetAllComments(ctx context.Context, params core.GetAllCommentsParams) ([]core.Comment, int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAllComments")
	}

	var r0 []core.Comment
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, core.GetAllCommentsParams) ([]core.Comment, int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.GetAllCommentsParams) []core.Comment); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.GetAllCommentsParams) int); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, core.GetAllCommentsParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCommentService_GetAllComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllComments'
type MockCommentService_GetAllComments_Call struct {
	*mock.Call
}

// GetAllComments is a helper method to define mock.On call
//   - ctx context.Context
//   - params core.GetAllCommentsParams
func (_e *MockCommentService_Expecter) GetAllComments(ctx interface{}, params interface{}) *MockCommentService_GetAllComments_Call {
	return &MockCommentService_GetAllComments_Call{Call: _e.mock.On("GetAllComments", ctx, params)}
}

func (_c *MockCommentService_GetAllComments_Call) Run(run func(ctx context.Context, params core.GetAllCommentsParams)) *MockCommentService_GetAllComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.GetAllCommentsParams))
	})
	return _c
}

func (_c *MockCommentService_GetAllComments_Call) Return(data []core.Comment, total int, err error) *MockCommentService_GetAllComments_Call {
	_c.Call.Return(data, total, err)
	return _c
}

func (_c *MockCommentService_GetAllComments_Call) RunAndReturn(run func(context.Context, core.GetAllCommentsParams) ([]core.Comment, int, error)) *MockCommentService_GetAllComments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function with given fields: ctx, comments
func (_m *MockCommentService) UpdateComment(ctx context.Context, comments core.Comment) (core.Comment, error) {
	ret := _m.Called(ctx, comments)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 core.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Comment) (core.Comment, error)); ok {
		return rf(ctx, comments)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Comment) core.Comment); ok {
		r0 = rf(ctx, comments)
	} else {
		r0 = ret.Get(0).(core.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Comment) error); ok {
		r1 = rf(ctx, comments)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentService_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockCommentService_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comments core.Comment
func (_e *MockCommentService_Expecter) UpdateComment(ctx interface{}, comments interface{}) *MockCommentService_UpdateComment_Call {
	return &MockCommentService_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, comments)}
}

func (_c *MockCommentService_UpdateComment_Call) Run(run func(ctx context.Context, comments core.Comment)) *MockCommentService_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Comment))
	})
	return _c
}

func (_c *MockCommentService_UpdateComment_Call) Return(data core.Comment, err error) *MockCommentService_UpdateComment_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockCommentService_UpdateComment_Call) RunAndReturn(run func(context.Context, core.Comment) (core.Comment, error)) *MockCommentService_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentService creates a new instance of MockCommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentService {
	mock := &MockCommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
