// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/kotopesp/sos-kotopes/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// PostService is an autogenerated mock type for the PostService type
type PostService struct {
	mock.Mock
}

// AddToFavourites provides a mock function with given fields: ctx, postFavourite
func (_m *PostService) AddToFavourites(ctx context.Context, postFavourite core.PostFavourite) (core.PostDetails, error) {
	ret := _m.Called(ctx, postFavourite)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.PostFavourite) core.PostDetails); ok {
		r0 = rf(ctx, postFavourite)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.PostFavourite) error); ok {
		r1 = rf(ctx, postFavourite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePost provides a mock function with given fields: ctx, postDetails
func (_m *PostService) CreatePost(ctx context.Context, postDetails core.PostDetails) (core.PostDetails, error) {
	ret := _m.Called(ctx, postDetails)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.PostDetails) core.PostDetails); ok {
		r0 = rf(ctx, postDetails)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.PostDetails) error); ok {
		r1 = rf(ctx, postDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFromFavourites provides a mock function with given fields: ctx, post
func (_m *PostService) DeleteFromFavourites(ctx context.Context, post core.PostFavourite) error {
	ret := _m.Called(ctx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.PostFavourite) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: ctx, post
func (_m *PostService) DeletePost(ctx context.Context, post core.Post) error {
	ret := _m.Called(ctx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Post) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPosts provides a mock function with given fields: ctx, userID, params
func (_m *PostService) GetAllPosts(ctx context.Context, userID int, params core.GetAllPostsParams) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, userID, params)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, core.GetAllPostsParams) []core.PostDetails); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, core.GetAllPostsParams) int); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, core.GetAllPostsParams) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetFavouritePosts provides a mock function with given fields: ctx, userID, params
func (_m *PostService) GetFavouritePosts(ctx context.Context, userID int, params core.GetAllPostsParams) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, userID, params)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, core.GetAllPostsParams) []core.PostDetails); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, core.GetAllPostsParams) int); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, core.GetAllPostsParams) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPostByID provides a mock function with given fields: ctx, postID, userID
func (_m *PostService) GetPostByID(ctx context.Context, postID int, userID int) (core.PostDetails, error) {
	ret := _m.Called(ctx, postID, userID)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int, int) core.PostDetails); ok {
		r0 = rf(ctx, postID, userID)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, postID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPosts provides a mock function with given fields: ctx, id
func (_m *PostService) GetUserPosts(ctx context.Context, id int) ([]core.PostDetails, int, error) {
	ret := _m.Called(ctx, id)

	var r0 []core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, int) []core.PostDetails); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PostDetails)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdatePost provides a mock function with given fields: ctx, updateRequestPost, updateRequestPhotos
func (_m *PostService) UpdatePost(ctx context.Context, updateRequestPost core.UpdateRequestPost, updateRequestPhotos core.UpdateRequestPhotos) (core.PostDetails, error) {
	ret := _m.Called(ctx, updateRequestPost, updateRequestPhotos)

	var r0 core.PostDetails
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateRequestPost, core.UpdateRequestPhotos) core.PostDetails); ok {
		r0 = rf(ctx, updateRequestPost, updateRequestPhotos)
	} else {
		r0 = ret.Get(0).(core.PostDetails)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, core.UpdateRequestPost, core.UpdateRequestPhotos) error); ok {
		r1 = rf(ctx, updateRequestPost, updateRequestPhotos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPostService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostService creates a new instance of PostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostService(t mockConstructorTestingTNewPostService) *PostService {
	mock := &PostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
